version: '3'
services:
  web:
    build: 
      context: ../../
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/postgres
    ports:
      - "80:3000"
    links:
      - db

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
